In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
a = np.array([2,4,6,8,10])

In [6]:
a

array([ 2,  4,  6,  8, 10])

In [9]:
np.linspace(1, 10, 15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(8, 15, 2)

array([ 8, 10, 12, 14])

In [19]:
a= np.ones([5, 4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
v = np.zeros([5,4])
v

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
b = np.array(
    [
    [1,3,5],
    [2,6,9],
    [10,11,12]
    ]
)
b

array([[ 1,  3,  5],
       [ 2,  6,  9],
       [10, 11, 12]])

In [30]:
b[1][2] = 20

In [31]:
b

array([[ 1,  3,  5],
       [ 2,  6, 20],
       [10, 11, 12]])

In [32]:
b[:, 2]

array([ 5, 20, 12])

In [39]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [37]:
np.random.randint(low=0, high=10, size=(5,2))

array([[3, 5],
       [8, 4],
       [6, 3],
       [9, 2],
       [0, 4]])

In [41]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [43]:
d = 10 * (c + 10) - (5 - c)
d

array([ 95, 106, 117, 128, 139])

In [44]:
c+d

array([ 95, 107, 119, 131, 143])

In [45]:
c> 2

array([False, False, False,  True,  True])

In [46]:
c[c>2]

array([3, 4])

In [48]:
d[d % 2 == 0]

array([106, 128])

In [49]:
c>d

array([False, False, False, False, False])

In [52]:
c[d>c]

array([0, 1, 2, 3, 4])

In [54]:
d.max()

np.int64(139)

In [55]:
d.min()

np.int64(95)

In [56]:
d.std()

np.float64(15.556349186104045)

In [57]:
d.var()

np.float64(242.0)

In [59]:
d.shape

(5,)

In [60]:
c.shape

(5,)

In [65]:
d, c

(array([ 95, 106, 117, 128, 139]), array([0, 1, 2, 3, 4]))

In [66]:
d * c

array([  0, 106, 234, 384, 556])

In [67]:
d ** c

array([        1,       106,     13689,   2097152, 373301041])

In [77]:
def vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0]

    m = a.shape[0]
    mul = 0.0

    for i in range(m):
        mul = mul + a[i] * b[i]

    return mul

In [73]:
val1 = np.arange(4) + 1
val1

array([1, 2, 3, 4])

In [74]:
val2 = (np.arange(4) + 1) * 2
val2

array([2, 4, 6, 8])

In [78]:
vector_multiplication(val1, val2)

np.float64(60.0)

In [79]:
val1.dot(val2)

np.int64(60)

In [98]:
def matrix_vector_multiplication(a,b):
    assert a.shape[1] == b.shape[0]

    m = a.shape[0]
    result = np.zeros(m)

    for i in range(m):
        result[i] = vector_multiplication(a[i], b)

    return result

In [92]:
U = np.random.randint(low=1, high=4, size=(3,4))
U

array([[3, 2, 3, 1],
       [3, 2, 3, 2],
       [2, 1, 2, 3]])

In [93]:
v = np.arange(4) + 1
v

array([1, 2, 3, 4])

In [99]:
matrix_vector_multiplication(U, v)

array([20., 24., 22.])

In [95]:
U @ v

array([20, 24, 22])

In [133]:
def matrix_matrix_multiplication(a,b):
    assert a.shape[1] == b.shape[0]

    num_rows = a.shape[0]
    num_cols = b.shape[1]
    result = np.zeros((num_rows, num_cols))

    for i in range(num_rows):
        result[:, i] = matrix_vector_multiplication(a, b[:, i])

    return result

In [127]:
W = np.random.randint(low=1, high=4, size=(3,4))
W

array([[3, 1, 3, 1],
       [1, 3, 1, 1],
       [1, 3, 2, 2]])

In [113]:
X = np.random.randint(low=3, high=8, size=(4,3))
X

array([[3, 3, 6],
       [5, 5, 5],
       [4, 6, 7],
       [6, 4, 3]])

In [130]:
X.shape[0]

4

In [134]:
matrix_matrix_multiplication(W,X)

array([[32., 36., 47.],
       [28., 28., 31.],
       [38., 38., 41.]])

In [135]:
W.dot(X)

array([[32, 36, 47],
       [28, 28, 31],
       [38, 38, 41]])

In [136]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [142]:
Z = np.random.randint(low=3, high=10, size=(4,4))
Z

array([[4, 4, 4, 6],
       [3, 3, 3, 5],
       [3, 8, 6, 8],
       [3, 9, 6, 9]])

In [143]:
Z * np.eye(4)

array([[4., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 9.]])

In [144]:
Z.dot(np.eye(4))

array([[4., 4., 4., 6.],
       [3., 3., 3., 5.],
       [3., 8., 6., 8.],
       [3., 9., 6., 9.]])

In [145]:
Zinv = np.linalg.inv(Z)
Zinv

array([[ 2.        , -2.        , -1.        ,  0.66666667],
       [ 1.5       , -2.        , -1.        ,  1.        ],
       [-1.        ,  1.        ,  2.        , -1.66666667],
       [-1.5       ,  2.        ,  0.        ,  0.        ]])

In [146]:
Zinv.dot(Z)

array([[ 1.00000000e+00, -1.33226763e-15, -8.88178420e-16,
        -1.33226763e-15],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 4.44089210e-16,  1.33226763e-15,  1.00000000e+00,
         1.33226763e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])